<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    
    <RootNamespace>$(SolutionName).Sample</RootNamespace>
    <AssemblyName>$(SolutionName).Sample</AssemblyName>

    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)\GeneratedFiles</CompilerGeneratedFilesOutputPath>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Main\Main.csproj" OutputItemType="Analyzer" />
    <PackageReference Include="MrMeeseeks.DIE.UserUtility" Version="3.0.1" />
  </ItemGroup>

</Project>
