using MrMeeseeks.DIE.Configuration.Attributes;
using MrMeeseeks.DIE.Extensions;
using MrMeeseeks.DIE.Validation.Range.UserDefined;

namespace MrMeeseeks.DIE.Validation.Range;

internal interface IValidateContainer : IValidateRange
{
}

internal class ValidateContainer : ValidateRange, IValidateContainer
{
    private readonly IValidateTransientScope _validateTransientScopeFactory;
    private readonly IValidateScope _validateScopeFactory;
    private readonly WellKnownTypesMiscellaneous _wellKnownTypesMiscellaneous;

    internal ValidateContainer(
        IValidateTransientScope validateTransientScopeFactory,
        IValidateScope validateScopeFactory,
        IValidateUserDefinedAddForDisposalSync validateUserDefinedAddForDisposalSync,
        IValidateUserDefinedAddForDisposalAsync validateUserDefinedAddForDisposalAsync,
        IValidateUserDefinedConstrParam validateUserDefinedConstrParam,
        IValidateUserDefinedFactoryMethod validateUserDefinedFactoryMethod,
        IValidateUserDefinedFactoryField validateUserDefinedFactoryField,
        WellKnownTypes wellKnownTypes,
        WellKnownTypesMiscellaneous wellKnownTypesMiscellaneous) 
        : base(
            validateUserDefinedAddForDisposalSync, 
            validateUserDefinedAddForDisposalAsync, 
            validateUserDefinedConstrParam, 
            validateUserDefinedFactoryMethod,
            validateUserDefinedFactoryField,
            wellKnownTypes)
    {
        _validateTransientScopeFactory = validateTransientScopeFactory;
        _validateScopeFactory = validateScopeFactory;
        _wellKnownTypesMiscellaneous = wellKnownTypesMiscellaneous;
    }

    public override IEnumerable<Diagnostic> Validate(INamedTypeSymbol rangeType, INamedTypeSymbol containerType)
    {
        foreach (var diagnostic in base.Validate(rangeType, containerType))
            yield return diagnostic;

        if (rangeType.GetTypeMembers(Constants.DefaultTransientScopeName, 0).FirstOrDefault() is
            { } defaultTransientScope)
            foreach (var diagnostic in _validateTransientScopeFactory.Validate(defaultTransientScope, rangeType))
                yield return diagnostic;

        foreach (var customTransientScope in rangeType
                     .GetTypeMembers()
                     .Where(nts => nts.Name.StartsWith(Constants.CustomTransientScopeName)))
            foreach (var diagnostic in _validateTransientScopeFactory.Validate(customTransientScope, rangeType))
                yield return diagnostic;

        if (rangeType.GetTypeMembers(Constants.DefaultScopeName, 0).FirstOrDefault() is
            { } defaultScope)
            foreach (var diagnostic in _validateScopeFactory.Validate(defaultScope, rangeType))
                yield return diagnostic;

        foreach (var customScope in rangeType
                     .GetTypeMembers()
                     .Where(nts => nts.Name.StartsWith(Constants.CustomScopeName)))
            foreach (var diagnostic in _validateScopeFactory.Validate(customScope, rangeType))
                yield return diagnostic;

        var createFunctionAttributes = rangeType
            .GetAttributes()
            .Where(ad =>
                SymbolEqualityComparer.Default.Equals(
                    ad.AttributeClass, 
                    _wellKnownTypesMiscellaneous.CreateFunctionAttribute))
            .ToImmutableArray();
        
        if (!createFunctionAttributes.Any())
            yield return ValidationErrorDiagnostic(rangeType, containerType, $"The container has to have at least one attribute of type \"{nameof(CreateFunctionAttribute)}\".");

        var takenMemberNames = new HashSet<string>();
        takenMemberNames.UnionWith(rangeType.MemberNames);

        foreach (var createFunctionAttribute in createFunctionAttributes)
        {
            var location = createFunctionAttribute.GetLocation();
            if (createFunctionAttribute.ConstructorArguments.Length == 2
                && createFunctionAttribute.ConstructorArguments[1].Value is string functionName)
            {
                if (functionName == nameof(IDisposable.Dispose))
                    yield return ValidationErrorDiagnostic(rangeType, $"Create function isn't allowed to have the name \"{nameof(IDisposable.Dispose)}\", because a method with that name may have to be generated by the container.", location);
                if (functionName == nameof(IAsyncDisposable.DisposeAsync))
                    yield return ValidationErrorDiagnostic(rangeType, $"Create function isn't allowed to have the name \"{nameof(IAsyncDisposable.DisposeAsync)}\", because a method with that name will be generated by the container.", location);

                foreach (var concreteFunctionName in new [] { $"{functionName}{Constants.CreateFunctionSuffix}", $"{functionName}{Constants.CreateFunctionSuffixAsync}", $"{functionName}{Constants.CreateFunctionSuffixValueAsync}"})
                {
                    if (takenMemberNames.Contains(concreteFunctionName))
                        yield return ValidationErrorDiagnostic(rangeType, $"Create function's name \"{concreteFunctionName}\" collides with one of the other members of the container class.", location);
                    takenMemberNames.Add(concreteFunctionName);
                }
            }
            else
                yield return ValidationErrorDiagnostic(rangeType, "Attribute doesn't have expected constructor arguments.", location);
        }
    }

    protected override Diagnostic ValidationErrorDiagnostic(INamedTypeSymbol rangeType, INamedTypeSymbol _, string specification) => 
        Diagnostics.ValidationContainer(rangeType, specification);
    
    private Diagnostic ValidationErrorDiagnostic(INamedTypeSymbol rangeType, string specification, Location location) => 
        Diagnostics.ValidationContainer(rangeType, specification, location);
}