name: OnVersionTag

on:
  push:
    tags:
      - '*'
jobs:
  windows:
    
    strategy:
      matrix:
        configuration: [ Release ]
    runs-on: windows-latest

    env:
      Solution_Name: MrMeeseeks.DIE.sln
      
    steps:
    - uses: actions/checkout@main
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 9.0.100
    - run: set DOTNET_CLI_TELEMETRY_OPTOUT=1
    - name: Install dependencies
      run: dotnet restore .\MrMeeseeks.DIE.sln
    - name: Build
      run: dotnet build .\MrMeeseeks.DIE.sln --configuration Release --no-restore
    - name: Test Configuration
      run: dotnet test .\Test.Configuration\Test.Configuration.csproj --no-restore --verbosity normal
    - name: Test Interface Interception
      run: dotnet test .\Test.InterfaceInterception\Test.InterfaceInterception.csproj --no-restore --verbosity normal
    - name: Test Wrappers
      run: dotnet test .\Test.Wrappers\Test.Wrappers.csproj --no-restore --verbosity normal
    - name: Test Injection
      run: dotnet test .\Test.Injection\Test.Injection.csproj --no-restore --verbosity normal
    - name: Test
      run: dotnet test .\Test\Test.csproj --no-restore --verbosity normal
    - name: Publish to NuGet
      uses: Yeah69/publish-nuget@main
      with:
        PROJECT_FILE_PATH: Main/Main.csproj
        VERSION_FILE_PATH: Directory.Build.props
        TAG_COMMIT: false
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
